vlan-project/vlan/applications/vlan/urls.py
from django.urls import path
# Importamos las vistas 
from . import views

app_name = 'vlan_app'

urlpatterns = [
     # URL de la página principal
    path(
         '', 
         views.VlanSearchView.as_view(),
         name = 'vlan-index',
    ), 
    path(
         'listAllVlans/', 
         views.VlanListView.as_view(),
         name = 'vlan-list',
    ), 
    path(
         'vlanUpdate/<int:pk>/', 
         views.VlanUpdateView.as_view(),
         name = 'vlan-update',
    ), 
    path(
         'vlanMenu/', 
         views.VlanView.as_view(),
         name = 'vlan-menu',
    ),
    path(
         'vlanCreate/', 
         views.VlanCreateView.as_view(),
         name = 'vlan-create',
    ),  
    path(
        'vlanDelete/<int:pk>/',
        views.VlanDeleteView.as_view(),
        name='vlan-delete'
    ),
]

vlan-project/vlan/vlan/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Applications urls
    re_path('', include('applications.vlan.urls')),
]

vlan-project/vlan/applications/vlan/models.py
from django.db import models

# Create your models here.

class Interfaces(models.Model):

    name = models.CharField(
        'Interface Name',
         max_length = 20
    )

    class meta:
        verbose_name = 'Interface'
        verbose_name_plural = 'Interfaces'

    def __str__(self):
        return self.name
    

class Vlan(models.Model):
    
    name = models.CharField(
        'Vlan Name',
         max_length = 40
    )

    network = models.CharField(
        'Network',
         max_length = 40
    )

    mask = models.CharField(
        'Mask',
         max_length = 40
    )

    gateway = models.CharField(
        'Gateway',
         max_length = 40,
         blank = True
    )

    number = models.CharField(
        'Number',
         max_length = 5
    )

    interfaces = models.ManyToManyField(Interfaces)

    def __str__(self):
        return self.name + ' - ' + self.network

    

    



   

vlan-project/vlan/applications/vlan/forms.py
from django import forms
from .models import Vlan

# Los Formularios Simples no trabajan con un modelo en particular
class VlanForm(forms.Form):
    
    ssh_user = forms.CharField(
        max_length=30,
        required = True
    )
    
    ssh_pass = forms.CharField(
        max_length=30,
        required = True
    )

# Creamos un formulario que dependa en un modelo 'Model Form'
class NewVlanForm(forms.ModelForm):
    class Meta:
        model = Vlan
        fields = (
            'name',
            'network',
            'mask',
            'number',
            'interfaces'   
        )

        # Si queremos personalizar un campo de un formulario debemos utilizar widgets
        widgets = {
            'interfaces': forms.CheckboxSelectMultiple()
        }

vlan-project/vlan/applications/vlan/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.views.generic.edit import FormView
from django.urls import reverse_lazy

from django.views.generic import (
    ListView,
    UpdateView,
    TemplateView,
    CreateView,
    DeleteView,
)

# Importamos los modelos locales
from .models import Interfaces, Vlan
from .forms import VlanForm, NewVlanForm
from .utils import (
    getDataVlan,
    getVlanGateway,
    createVlanGNS3,
    assignInterfacesVlan,
    deleteVlanGNS3,
    createSubInterfaz,
    deleteSubInterfaz
)

from .conexion import make_ssh_conexion

address_1 = '192.168.1.11'
address_2 = '192.168.1.12'
address_3 = '192.168.1.13'
address_4 = '192.168.1.1'


class VlanSearchView(FormView):

    template_name = 'vlan/index.html'
    form_class  = VlanForm
    success_url = reverse_lazy('vlan_app:vlan-menu')

    def form_valid(self, form):
        print(' ======== FORM VALID ========')

        ssh_user = form.cleaned_data['ssh_user']
        ssh_pass = form.cleaned_data['ssh_pass']

        global session_1
        session_1 = make_ssh_conexion( address_1, ssh_user, ssh_pass )

        global session_2
        session_2 = make_ssh_conexion( address_2, ssh_user, ssh_pass )

        global session_3
        session_3 = make_ssh_conexion( address_3, ssh_user, ssh_pass )

        global session_4
        session_4 = make_ssh_conexion( address_4, ssh_user, ssh_pass )

        val = getDataVlan( session_1 )
        if val:
            print('All the data was saved in the database')

        return super(VlanSearchView,self).form_valid(form)

class VlanListView(ListView):
    template_name = 'vlan/vlan_list.html'
    model = Vlan
    context_object_name = 'vlans'
    ordering = 'id'


class VlanView(TemplateView):
    template_name = 'vlan/vlan_menu.html'


class VlanUpdateView(UpdateView):
    template_name = 'vlan/vlan_update.html'
    model = Vlan
    success_url = reverse_lazy('vlan_app:vlan-list')
    fields = (
        'interfaces',
    )

    def form_valid(self, form):
        print(' ======== FORM VALID ========')
        vlan = form.save( commit = False )
         # Setting up all the interfaces in all the switches
        interfaces = list()
        for interface in form.cleaned_data['interfaces']:
            interfaces.append(interface)
        vlan_number = vlan.number
        print(f'VLAN number: { vlan_number }')
        # Assigning all the interfaces for the VLAN
        command_interfaces = [ f'int {interface}' for interface in interfaces]
        assignInterfacesVlan( session_1, command_interfaces, vlan_number)
        assignInterfacesVlan( session_2, command_interfaces, vlan_number)
        assignInterfacesVlan( session_3, command_interfaces, vlan_number)
        print('All the interfaces were created successfully in GNS3')
        # Retrieving only the Vlan One
        Vlan.objects.get(
            number = '1'
        ).interfaces.remove(*interfaces)

        return super( VlanUpdateView, self ).form_valid(form)


class VlanCreateView(CreateView):
    template_name = 'vlan/vlan_create.html'
    model = Vlan
    form_class = NewVlanForm
    success_url = reverse_lazy('vlan_app:vlan-list')

    def form_valid(self, form):
        print(' ======== FORM VALID ========')
        vlan = form.save( commit = False )
        network = vlan.network
        vlan_gateway = getVlanGateway( network )
        vlan.gateway = vlan_gateway
        vlan.save()
        # Setting up all the interfaces in all the switches
        interfaces = list()
        for interface in form.cleaned_data['interfaces']:
            interfaces.append(interface)

        vlan_number = form.cleaned_data['number']
        vlan_name   = form.cleaned_data['name']
        vlan_mask   = form.cleaned_data['mask']
        # Creating the Vlan in GNS3
        createVlanGNS3( session_1, vlan_number, vlan_name, vlan_gateway, vlan_mask )
        print('Vlan created successfully in GNS3')
        # Assigning all the interfaces for the VLAN
        command_interfaces = [ f'int {interface}' for interface in interfaces]
        assignInterfacesVlan( session_1, command_interfaces, vlan_number)
        assignInterfacesVlan( session_2, command_interfaces, vlan_number)
        assignInterfacesVlan( session_3, command_interfaces, vlan_number)
        print('All the interfaces were created successfully in GNS3')
        createSubInterfaz( session_4, vlan_number, vlan_gateway, vlan_mask )
        print('The subinterfaz in the router was created successfully')
        # Retrieving only the Vlan One
        Vlan.objects.get(
            number = '1'
        ).interfaces.remove(*interfaces)

        return super( VlanCreateView, self ).form_valid(form)


class VlanDeleteView(DeleteView):
    template_name = 'vlan/vlan_delete.html'
    model = Vlan
    success_url = reverse_lazy('vlan_app:vlan-list')

    # Recuperamos el objeto que al que se hace referencia en la URL
    def get_object(self):
        #Obtenemos el 'pk' que se manda en la URL a través del diccionario kwargs
        id_ = self.kwargs.get('pk')
        return get_object_or_404( Vlan, id = id_ )

    def delete(self,request,*args,**kwargs):
        # Obtenemos el objeto que se especifica en la url
        self.object = self.get_object()
        # Obtenemos todas las interfaces ligadas a esta VLAN
        interfaces = self.object.interfaces.all()
        command_interfaces = [ f'int {interface}' for interface in interfaces ]
        # Eliminamos la VLAN de GNS3
        vlan_number = self.object.number
        deleteVlanGNS3( session_1, vlan_number )
        print(f'The vlan {vlan_number} was deleted successfully')
        # Asignamos las interfaces de esta VLAN a la VLAN 1
        if interfaces:
            assignInterfacesVlan( session_1, command_interfaces )
            assignInterfacesVlan( session_2, command_interfaces )
            assignInterfacesVlan( session_3, command_interfaces )
            print('All the interfaces of this Vlan were returned to their original one')
        else:
            print('No interfaces detected')

        deleteSubInterfaz( session_4, vlan_number )
        print('The subinterfaz in the router was deleted successfully')
        # Adding the interfaces of this Vlan to the original one
        Vlan.objects.get(
            number = '1'
        ).interfaces.add(*interfaces)

        # Eliminamos el objeto del modelo de la BD
        self.object.delete()

        return HttpResponseRedirect( self.success_url )

vlan-project/vlan/templates/vlan/index.html
<!-- Heredamos todo lo que van a tener en común todos nuestros templates -->
{% extends "base.html" %}
<!-- Cargamos nuestros archivos estáticos que se encuentran en la carpeta 'statics' -->
{% load  static %}

{% block content %}
    <div class="grid-container">
        <div class="grid-x">
            <h3 class="cell" style="margin-top: 24px; text-align: center;"> SSH Login </h3>
            <form class="cell grid-x grid-margin-x align-center" method="POST" autocomplete="off"> {% csrf_token %}
                <div class="cell large-8">
                    <label> SSH Username:
                        {{ form.ssh_user }}
                    </label>
                </div>
                <div class="cell large-8">
                    <label> SSH Password:
                    {{ form.ssh_pass }}
                    </label>
                </div>
                <div class="cell" style="text-align: center;">
                    <button type="submit" class="button" style="width: 132px;"> Login </button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

vlan-project/vlan/templates/vlan/vlan_create.html
<!-- Heredamos todo lo que van a tener en común todos nuestros templates -->
{% extends "base.html" %}
<!-- Cargamos nuestros archivos estáticos que se encuentran en la carpeta 'statics' -->
{% load  static %}

{% block content %}
    <div class="grid-container">
        <div class="grid-x">
            <h3 class="cell" style="margin-top: 24px; text-align: center;"> Register New Vlan </h3>
            <form class="cell grid-x grid-margin-x align-center" method="POST" autocomplete="off"> {% csrf_token %}
                <div class="cell large-6">
                    <label> Vlan Name:
                        {{ form.name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label> Vlan Number:
                        {{ form.number }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label> Vlan Network:
                    {{ form.network }}
                    </label>
                </div>

                <div class="cell large-6">
                    <label> Vlan Mask:
                    {{ form.mask }}
                    </label>
                </div>

                <div class="cell large-2">
                    <label> Vlan Interfaces:
                        {{ form.interfaces }}
                    </label>
                </div>

                <div class="cell" style="text-align: center;">
                    <button type="submit" class="button" style="width: 132px;"> Create Vlan </button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}
    

vlan-project/vlan/templates/vlan/vlan_delete.html
{% extends "base.html" %}
{% load  static %}

<!-- Body -->
{% block content %}
    <!-- Content -->
    <div class="grid-container">
        <div class="grid-x" style="margin-top: 24px;">
           <!-- 'object' hace referencia al registro de la BD especificado en la URL por el pk--> 
            <h3 class="cell"> Delete Vlan: {{ object.name }} </h3>
            <form class="cell" method="POST"> {% csrf_token %}
                <div class="callout alert grid-x grid-padding-x">
                    <h5 class="cell large-6"> Do you want to delete this Vlan? </h5>
                    <button type="submit" class="alert button cell large-2"> Delete </button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

vlan-project/vlan/templates/vlan/vlan_list.html
<!-- Heredamos todo lo que van a tener en común todos nuestros templates -->
{% extends "base.html" %}
<!-- Cargamos nuestros archivos estáticos que se encuentran en la carpeta 'statics' -->
{% load  static %}

{% block content %}
    <!-- Al indicar class="grid-container" en el div esto nos proporciona margenes 
    a la izquierda y derecha, así como centrar los componentes -->
    <div class="grid-container" style="margin-top: 24px;">
        <!-- Creamos un lienzo de foundation 12 columnas, con separación entre los elementos
        creados del grid-container -->
        <div class="grid-x grid-margin-x"> 
            <h3 class="cell" style="text-align: center;" > Registered Vlans: </h3>
            {% for vlan in vlans  %}
                <div class="card cell large-4" style="width: 300px;">
                    <div class="card-divider label primary">
                        <h4 class="cell" style="text-align: center;" > {{ vlan.name }} : {{ vlan.number }} </h4>
                    </div>
                    <div class="card-section">
                        <p> Network: {{ vlan.network }} </p>
                        <p> Mask: {{ vlan.mask }} </p>
                        <p> Gateway: {{ vlan.gateway }} </p>
                        <p> Interfaces: </p> 
                            <ul>
                                {% for interface in vlan.interfaces.all %}
                                    <li> {{ interface }} </li>    
                                {% empty %}
                                    <li> Not Assigned Yet </li>
                                {% endfor %}    
                            </ul>
                        
                        
                        {% ifnotequal vlan.number '1' %}
                            <div style="text-align: center;">
                                <!-- <a class="button warning" href="{% url 'vlan_app:vlan-update' vlan.id %}" > Update </a> -->
                                <a class="button alert" href="{% url 'vlan_app:vlan-delete' vlan.id %}" > Delete </a>
                            </div> 
                        {% endifnotequal %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    
{% endblock content %}
    

vlan-project/vlan/templates/vlan/vlan_menu.html
<!-- Heredamos todo lo que van a tener en común todos nuestros templates -->
{% extends "base.html" %}
<!-- Cargamos nuestros archivos estáticos que se encuentran en la carpeta 'statics' -->
{% load  static %}

{% block content %}
    <div class="grid-container" style="margin-top: 24px; text-align: center;">
        <h3 class="cell"> - Vlan Menu - </h3>
        <ul>
            <li>
                <a class="button" href="{% url 'vlan_app:vlan-list' %}"> List All Vlans </a>
            </li>
            
            <li>
                <a class="button" href="{% url 'vlan_app:vlan-create' %}"> Create Vlan </a>
            </li>

            <li>
                <a class="button" href="{% url 'vlan_app:vlan-list' %}"> Delete Vlan </a>
            </li>

        </ul>
        
        
    </div>
{% endblock content %}
    

vlan-project/vlan/templates/vlan/vlan_update.html
<!-- Heredamos todo lo que van a tener en común todos nuestros templates -->
{% extends "base.html" %}
<!-- Cargamos nuestros archivos estáticos que se encuentran en la carpeta 'statics' -->
{% load  static %}

{% block content %}
<div class="grid-container">
    <div class="grid-x">
        <h3 class="cell" style="margin-top: 24px; text-align: center;"> Update Vlan {{ object.name }} Interfaces </h3>
        <form class="cell grid-x grid-margin-x align-center" method="POST" autocomplete="off"> {% csrf_token %}
            {{ form.interfaces }}
            <div class="cell" style="text-align: center;">
                <button type="submit" class="button" style="width: 132px;"> Update Vlan </button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}